I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day3.rpy", line 334, in <module>
    scene day3 forest pickup frame3 with shake
NameError: name 'shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "lib/windows-i686/day3.rpyc", line 334, in script
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\ast.py", line 1271, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\python.py", line 1725, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\satel\Downloads\renpy-6.99.12.2-sdk\renpy\python.py", line 1719, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/day3.rpy", line 334, in <module>
    scene day3 forest pickup frame3 with shake
NameError: name 'shake' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.2.2029
UserInterface 0.0
