I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ending/wedding-papyrus.rpy", line 84, in script call
    call mettatonWeddingSurprised
  File "game/ending/wedding-papyrus.rpy", line 84, in script call
    call mettatonWeddingSurprised
ScriptError: could not find label 'mettatonWeddingSurprised'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ending/wedding-papyrus.rpy", line 84, in script call
    call mettatonWeddingSurprised
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1436, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/ending/wedding-papyrus.rpy", line 84, in script call
    call mettatonWeddingSurprised
  File "/Applications/renpy-7.3.5-sdk/renpy/script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'mettatonWeddingSurprised'.

Darwin-19.5.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
User Interface 0.3.1
Thu Jul 16 21:44:46 2020
