I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day2.rpy", line 30, in script call
    call mettatonFashionShow from _call_mettatonFashionShow
  File "game/ending/wedding-papyrus.rpy", line 38, in script
    mettaton "What?!"
Exception: Sayer 'mettaton' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day2.rpy", line 30, in script call
    call mettatonFashionShow from _call_mettatonFashionShow
  File "game/ending/wedding-papyrus.rpy", line 38, in script
    mettaton "What?!"
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\satel\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'mettaton' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
User Interface 0.3.1
Sun May 03 17:50:07 2020
